-- ============================================================
-- Migration: 027_update_manual_order_status_cancel_certificate.sql
-- Description: Aligns Manual Order EasyParcel statuses with EasyParcel OpenAPI,
--              and stores optional payment certificate/proof uploads.
-- Note: If your MySQL/MariaDB version does not support IF NOT EXISTS for ADD COLUMN,
--       run only the missing column lines manually.
-- ============================================================

ALTER TABLE `manual_orders`
    MODIFY COLUMN `status` VARCHAR(50) NOT NULL DEFAULT 'CREATED',
    MODIFY COLUMN `shipment_status` VARCHAR(50) NOT NULL DEFAULT 'CREATED';

ALTER TABLE `manual_orders`
    ADD COLUMN IF NOT EXISTS `payment_certificate_url` LONGTEXT NULL AFTER `platform_fee`,
    ADD COLUMN IF NOT EXISTS `payment_certificate_filename` VARCHAR(255) NULL AFTER `payment_certificate_url`;

UPDATE `manual_orders`
SET `status` = CASE UPPER(`status`)
    WHEN 'PUSHING' THEN 'BOOKING_PENDING'
    WHEN 'PUSHED' THEN 'SCHEDULE_IN_ARRANGEMENT'
    WHEN 'SHIPMENT_BOOKED' THEN 'SCHEDULE_IN_ARRANGEMENT'
    WHEN 'AWB_READY' THEN 'SCHEDULE_IN_ARRANGEMENT'
    WHEN 'PENDING_AWB' THEN 'SCHEDULE_IN_ARRANGEMENT'
    WHEN 'PENDING_PICKUP' THEN 'TO_BE_COLLECTED'
    WHEN 'PENDING_COLLECTION' THEN 'TO_BE_COLLECTED'
    WHEN 'DROPPED_OFF' THEN 'DROP_OFF'
    WHEN 'IN_TRANSIT' THEN 'DELIVERY_IN_TRANSIT'
    WHEN 'DELIVERY_ATTEMPTED' THEN 'DELIVERY_IN_TRANSIT'
    WHEN 'ON_HOLD' THEN 'DELIVERY_ON_HOLD'
    WHEN 'RETURNED_TO_SENDER' THEN 'RETURNED'
    WHEN 'FAILED' THEN 'BOOKING_FAILED'
    WHEN 'WITHDRAWN' THEN 'CANCELLED'
    ELSE UPPER(`status`)
END
WHERE `status` IS NOT NULL;

UPDATE `manual_orders`
SET `shipment_status` = CASE UPPER(`shipment_status`)
    WHEN 'PUSHING' THEN 'BOOKING_PENDING'
    WHEN 'PUSHED' THEN 'SCHEDULE_IN_ARRANGEMENT'
    WHEN 'SHIPMENT_BOOKED' THEN 'SCHEDULE_IN_ARRANGEMENT'
    WHEN 'AWB_READY' THEN 'SCHEDULE_IN_ARRANGEMENT'
    WHEN 'PENDING_AWB' THEN 'SCHEDULE_IN_ARRANGEMENT'
    WHEN 'PENDING_PICKUP' THEN 'TO_BE_COLLECTED'
    WHEN 'PENDING_COLLECTION' THEN 'TO_BE_COLLECTED'
    WHEN 'DROPPED_OFF' THEN 'DROP_OFF'
    WHEN 'IN_TRANSIT' THEN 'DELIVERY_IN_TRANSIT'
    WHEN 'DELIVERY_ATTEMPTED' THEN 'DELIVERY_IN_TRANSIT'
    WHEN 'ON_HOLD' THEN 'DELIVERY_ON_HOLD'
    WHEN 'RETURNED_TO_SENDER' THEN 'RETURNED'
    WHEN 'FAILED' THEN 'BOOKING_FAILED'
    WHEN 'WITHDRAWN' THEN 'CANCELLED'
    ELSE UPPER(`shipment_status`)
END
WHERE `shipment_status` IS NOT NULL;

UPDATE `manual_order_status_history`
SET `new_status` = CASE UPPER(`new_status`)
    WHEN 'PUSHING' THEN 'BOOKING_PENDING'
    WHEN 'PUSHED' THEN 'SCHEDULE_IN_ARRANGEMENT'
    WHEN 'SHIPMENT_BOOKED' THEN 'SCHEDULE_IN_ARRANGEMENT'
    WHEN 'AWB_READY' THEN 'SCHEDULE_IN_ARRANGEMENT'
    WHEN 'PENDING_AWB' THEN 'SCHEDULE_IN_ARRANGEMENT'
    WHEN 'PENDING_PICKUP' THEN 'TO_BE_COLLECTED'
    WHEN 'PENDING_COLLECTION' THEN 'TO_BE_COLLECTED'
    WHEN 'DROPPED_OFF' THEN 'DROP_OFF'
    WHEN 'IN_TRANSIT' THEN 'DELIVERY_IN_TRANSIT'
    WHEN 'DELIVERY_ATTEMPTED' THEN 'DELIVERY_IN_TRANSIT'
    WHEN 'ON_HOLD' THEN 'DELIVERY_ON_HOLD'
    WHEN 'RETURNED_TO_SENDER' THEN 'RETURNED'
    WHEN 'FAILED' THEN 'BOOKING_FAILED'
    WHEN 'WITHDRAWN' THEN 'CANCELLED'
    WHEN 'CANCEL' THEN 'CANCELLED'
    ELSE UPPER(`new_status`)
END
WHERE `new_status` IS NOT NULL;


UPDATE `manual_order_status_history`
SET `old_status` = CASE UPPER(`old_status`)
    WHEN 'PUSHING' THEN 'BOOKING_PENDING'
    WHEN 'PUSHED' THEN 'SCHEDULE_IN_ARRANGEMENT'
    WHEN 'SHIPMENT_BOOKED' THEN 'SCHEDULE_IN_ARRANGEMENT'
    WHEN 'AWB_READY' THEN 'SCHEDULE_IN_ARRANGEMENT'
    WHEN 'PENDING_AWB' THEN 'SCHEDULE_IN_ARRANGEMENT'
    WHEN 'PENDING_PICKUP' THEN 'TO_BE_COLLECTED'
    WHEN 'PENDING_COLLECTION' THEN 'TO_BE_COLLECTED'
    WHEN 'DROPPED_OFF' THEN 'DROP_OFF'
    WHEN 'IN_TRANSIT' THEN 'DELIVERY_IN_TRANSIT'
    WHEN 'DELIVERY_ATTEMPTED' THEN 'DELIVERY_IN_TRANSIT'
    WHEN 'ON_HOLD' THEN 'DELIVERY_ON_HOLD'
    WHEN 'RETURNED_TO_SENDER' THEN 'RETURNED'
    WHEN 'FAILED' THEN 'BOOKING_FAILED'
    WHEN 'WITHDRAWN' THEN 'CANCELLED'
    WHEN 'CANCEL' THEN 'CANCELLED'
    ELSE UPPER(`old_status`)
END
WHERE `old_status` IS NOT NULL;
