CREATE TABLE IF NOT EXISTS platform_manual_orders (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    company_id INT UNSIGNED NOT NULL,
    warehouse_id INT UNSIGNED NOT NULL,
    order_number VARCHAR(100) NOT NULL,
    order_time VARCHAR(10) NOT NULL,
    order_date DATE NOT NULL,
    waybill_file_name VARCHAR(255) NOT NULL,
    waybill_url LONGTEXT NOT NULL,
    shipment_status VARCHAR(50) NOT NULL DEFAULT 'Processed',
    logistic JSON NOT NULL,
    sender JSON NOT NULL,
    buyer JSON NOT NULL,
    package_details JSON NULL,
    created_by INT UNSIGNED NULL,
    deleted_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_platform_manual_orders_company_order (company_id, order_number),
    KEY idx_pmo_company_warehouse (company_id, warehouse_id),
    KEY idx_pmo_company_status (company_id, shipment_status),
    KEY idx_pmo_company_order_date (company_id, order_date),
    CONSTRAINT fk_pmo_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_pmo_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS platform_manual_order_items (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    company_id INT UNSIGNED NOT NULL,
    platform_manual_order_id BIGINT UNSIGNED NOT NULL,
    merchant_sku_id INT UNSIGNED NOT NULL,
    warehouse_id INT UNSIGNED NOT NULL,
    sku VARCHAR(100) NOT NULL,
    product_name VARCHAR(255) NULL,
    quantity INT UNSIGNED NOT NULL,
    unit_price DECIMAL(15,2) NOT NULL DEFAULT 0,
    weight DECIMAL(12,3) NULL,
    qty_on_hand_before INT NULL,
    qty_on_hand_after INT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_pmoi_company (company_id),
    KEY idx_pmoi_order (platform_manual_order_id),
    KEY idx_pmoi_merchant_sku (merchant_sku_id),
    KEY idx_pmoi_sku (sku),
    CONSTRAINT fk_pmoi_order FOREIGN KEY (platform_manual_order_id) REFERENCES platform_manual_orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_pmoi_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_pmoi_merchant_sku FOREIGN KEY (merchant_sku_id) REFERENCES merchant_skus(id) ON DELETE RESTRICT,
    CONSTRAINT fk_pmoi_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
