ALTER TABLE `warehouses`
    ADD COLUMN IF NOT EXISTS `city` VARCHAR(100) NULL AFTER `location`,
    ADD COLUMN IF NOT EXISTS `state` VARCHAR(100) NULL AFTER `city`,
    ADD COLUMN IF NOT EXISTS `zip_code` VARCHAR(30) NULL AFTER `state`;
