CREATE TABLE IF NOT EXISTS return_orders (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    company_id INT UNSIGNED NOT NULL,
    platform ENUM('manual','shopee','tiktok') NOT NULL DEFAULT 'manual',
    platform_store_id INT UNSIGNED NULL,
    store_name VARCHAR(255) NULL,
    platform_return_id VARCHAR(100) NULL,
    platform_order_id VARCHAR(100) NULL,
    order_number VARCHAR(100) NULL,
    warehouse_package_no VARCHAR(100) NULL,
    warehouse_id INT UNSIGNED NULL,
    platform_return_status VARCHAR(120) NULL,
    platform_status_label VARCHAR(120) NULL,
    erp_return_status VARCHAR(80) NOT NULL DEFAULT 'need_to_check',
    return_reason VARCHAR(255) NULL,
    return_reason_text VARCHAR(500) NULL,
    return_type VARCHAR(100) NULL,
    local_return_type VARCHAR(100) NULL,
    return_method VARCHAR(100) NULL,
    shipment_type VARCHAR(100) NULL,
    handover_method VARCHAR(100) NULL,
    return_tracking_number VARCHAR(150) NULL,
    return_provider_id VARCHAR(120) NULL,
    return_provider_name VARCHAR(255) NULL,
    logistic_name VARCHAR(255) NULL,
    return_warehouse_address TEXT NULL,
    remark TEXT NULL,
    refund_currency VARCHAR(10) NULL,
    refund_total DECIMAL(15,2) NULL,
    seller_next_action_json JSON NULL,
    discount_amount_json JSON NULL,
    shipping_fee_amount_json JSON NULL,
    raw_json JSON NULL,
    is_manual TINYINT(1) NOT NULL DEFAULT 0,
    is_resaleable_inbounded TINYINT(1) NOT NULL DEFAULT 0,
    resaleable_inbound_order_id INT UNSIGNED NULL,
    created_by INT UNSIGNED NULL,
    deleted_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_return_orders_platform_return (company_id, platform, platform_return_id),
    KEY idx_return_orders_company_platform (company_id, platform),
    KEY idx_return_orders_store (platform_store_id),
    KEY idx_return_orders_warehouse (warehouse_id),
    KEY idx_return_orders_order (company_id, platform_order_id),
    KEY idx_return_orders_status (company_id, erp_return_status),
    KEY idx_return_orders_updated (company_id, updated_at),
    CONSTRAINT fk_return_orders_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_return_orders_store FOREIGN KEY (platform_store_id) REFERENCES platform_stores(id) ON DELETE SET NULL,
    CONSTRAINT fk_return_orders_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
