CREATE TABLE IF NOT EXISTS return_order_lines (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    company_id INT UNSIGNED NOT NULL,
    return_order_id BIGINT UNSIGNED NOT NULL,
    merchant_sku_id INT UNSIGNED NULL,
    order_line_item_id VARCHAR(100) NULL,
    return_line_item_id VARCHAR(100) NULL,
    platform_sku_id VARCHAR(100) NULL,
    seller_sku VARCHAR(100) NULL,
    sku_name VARCHAR(255) NULL,
    product_name VARCHAR(500) NULL,
    product_image_url TEXT NULL,
    quantity INT UNSIGNED NOT NULL DEFAULT 1,
    refund_currency VARCHAR(10) NULL,
    refund_total DECIMAL(15,2) NULL,
    raw_json JSON NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_return_lines_return_line (return_order_id, return_line_item_id),
    KEY idx_return_lines_company (company_id),
    KEY idx_return_lines_order (return_order_id),
    KEY idx_return_lines_merchant_sku (merchant_sku_id),
    KEY idx_return_lines_seller_sku (seller_sku),
    CONSTRAINT fk_return_lines_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_return_lines_order FOREIGN KEY (return_order_id) REFERENCES return_orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_return_lines_merchant_sku FOREIGN KEY (merchant_sku_id) REFERENCES merchant_skus(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
